### PR TITLE
feat: Allow $set, $unset and $create_alias events

### PR DESCRIPTION
**Pull request by kehers**

### CODE REVIEW

**Comment by kehers** [comment]
Hi @tiina303, we added support for some custom PostHog events and would appreciate a merge.

Thanks.

**Comment by kehers** [comment]
Hi @tiina303, bubbling this up.

**Review by tiina303 — APPROVED** [review]

**Comment by tiina303** [comment]
hi sorry I was out on vacation, updated on our clouds now

**Comment by kehers** [comment]
> hi sorry I was out on vacation, updated on our clouds now

No problem at all. Thanks a lot.

**Pull request merged**
