### PR TITLE
Added option to filter type of event sent

### PR DESCRIPTION
**Pull request by kehers**

### CODE REVIEW

**Comment by kehers** [comment]
cc @MarconLP

**Review by tiina303 — CHANGES_REQUESTED** [review]
Hi we have some great news, we've been working improving our destination reliability. It's great because another destination behaving poorly won't be breaking the Engage destination in the future. To benefit from this we're going to need the app to be updated to be a `composeWebhook` app see [docs](https://posthog.com/docs/cdp/build/reference#composewebhook-function). Could you make the change to convert `onEvent`  to `composeWebhook`?

**Comment by kehers** [comment]
@tiina303 Thanks. I will take a look at this.

**Comment by kehers** [comment]
@tiina303 Done.

**Review by tiina303 — APPROVED** [review]
Looks good to me, thanks. Did you test this somehow already? 
Do you need to test this before I update our production cloud (if it doesn't work, then the events would be lost as we don't do backfills)?

**Comment by kehers** [comment]
@tiina303 Yes.

**Comment by tiina303** [comment]
sorry by yes you mean already tested or would like to test more before rolling to all users?

**Comment by kehers** [comment]
@tiina303 It is tested.

**Comment by tiina303** [comment]
I've updated our cloud prod environments

**Pull request merged**
